source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Brundlefly_Example', :exclusive => true do
  pod "Brundlefly", :path => "../"
end

target 'Brundlefly_Tests', :exclusive => true do
  pod "Brundlefly", :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '~> 3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
